/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class framebooking extends javax.swing.JFrame {

    /**
     * Creates new form framebooking
     */
    public framebooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeljudul = new javax.swing.JLabel();
        labelKode = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        labelWaktu = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNamaTeam = new javax.swing.JLabel();
        labelNope = new javax.swing.JLabel();
        ComboBoxKode = new javax.swing.JComboBox<>();
        jComboBoxTanggal = new javax.swing.JComboBox<>();
        ComboBoxBulan = new javax.swing.JComboBox<>();
        ComboBoxTahun = new javax.swing.JComboBox<>();
        jComboBoxMulai = new javax.swing.JComboBox<>();
        labelsampai = new javax.swing.JLabel();
        ComboBoxSelesai = new javax.swing.JComboBox<>();
        FieldNama = new javax.swing.JTextField();
        FieldNamaTeam = new javax.swing.JTextField();
        FieldNope = new javax.swing.JTextField();
        ButtonPesan = new javax.swing.JButton();
        ButtonHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labeljudul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeljudul.setText("BOOKING LAPANGAN FUTSAL");

        labelKode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKode.setText("Kode Booking");

        labelTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTanggal.setText("Tanggal Pemesanan");

        labelWaktu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelWaktu.setText("Waktu");

        labelNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNama.setText("Nama Pemesan");

        labelNamaTeam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNamaTeam.setText("Nama Team");

        labelNope.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope.setText("No Handphone");

        ComboBoxKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jComboBoxTanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal" }));
        jComboBoxTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTanggalActionPerformed(evt);
            }
        });

        ComboBoxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", " " }));

        ComboBoxTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));

        jComboBoxMulai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mulai" }));

        labelsampai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelsampai.setText("sampai");

        ComboBoxSelesai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selesai" }));

        FieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamaActionPerformed(evt);
            }
        });

        FieldNamaTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamaTeamActionPerformed(evt);
            }
        });

        FieldNope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNopeActionPerformed(evt);
            }
        });

        ButtonPesan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonPesan.setText("Pesan");
        ButtonPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesanActionPerformed(evt);
            }
        });

        ButtonHapus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ButtonHapus.setText("Hapus");
        ButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonHapusActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Waktu", "Nama Pemesan", "Nama Team", "No Handphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ButtonPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonHapus))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(labeljudul)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNope)
                                .addGap(90, 90, 90)
                                .addComponent(FieldNope, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelWaktu)
                                .addGap(257, 257, 257)
                                .addComponent(jComboBoxMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelsampai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNama)
                                .addGap(90, 90, 90)
                                .addComponent(FieldNama))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNamaTeam)
                                .addGap(112, 112, 112)
                                .addComponent(FieldNamaTeam))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTanggal)
                                    .addComponent(labelKode))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jComboBoxTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ComboBoxKode, 0, 257, Short.MAX_VALUE))))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labeljudul, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKode)
                    .addComponent(ComboBoxKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggal)
                    .addComponent(jComboBoxTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWaktu)
                    .addComponent(jComboBoxMulai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelsampai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(FieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaTeam)
                    .addComponent(FieldNamaTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNope)
                    .addComponent(FieldNope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonPesan)
                    .addComponent(ButtonHapus))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTanggalActionPerformed

    private void FieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamaActionPerformed

    private void FieldNamaTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamaTeamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamaTeamActionPerformed

    private void FieldNopeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNopeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNopeActionPerformed

    private void ButtonPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonPesanActionPerformed

    private void ButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framebooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonHapus;
    private javax.swing.JButton ButtonPesan;
    private javax.swing.JComboBox<String> ComboBoxBulan;
    private javax.swing.JComboBox<String> ComboBoxKode;
    private javax.swing.JComboBox<String> ComboBoxSelesai;
    private javax.swing.JComboBox<String> ComboBoxTahun;
    private javax.swing.JTextField FieldNama;
    private javax.swing.JTextField FieldNamaTeam;
    private javax.swing.JTextField FieldNope;
    private javax.swing.JComboBox<String> jComboBoxMulai;
    private javax.swing.JComboBox<String> jComboBoxTanggal;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelKode;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNamaTeam;
    private javax.swing.JLabel labelNope;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JLabel labelWaktu;
    private javax.swing.JLabel labeljudul;
    private javax.swing.JLabel labelsampai;
    // End of variables declaration//GEN-END:variables
}
