package Sewa;


import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public final class frameutama extends javax.swing.JFrame {

    /**
     * Creates new form frameutama
     */
     public SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd hh:mm");
       public Date dt = new Date();
       public Statement st;
       public ResultSet rs;
       public DefaultTableModel tabmodel;
       
       Connection cn = koneksi.koneksi.getKoneksi();
    public frameutama() {
        
        initComponents();
        judul();
        tampildata();
        tglhariini();
        harg();
       
        hrg_sewa.setText(null);
    }
    
     public void judul(){
    Object[] judul = {"Kd_Booking", "Tgl_Booking","Team","Manager","Status","Harga_Sewa","DP","Tgl_Sewa","Lama","Masuk","Keluar", "Total","sisa","Keterangan"};
    tabmodel = new DefaultTableModel(null, judul);
    tbldata.setModel(tabmodel);
    
    }
     
    public void tampildata(){
        
     try{
        cn = DriverManager.getConnection("jdbc:mysql://localhost/booking_lapangan?" + "user=root&password=");
        st = cn.createStatement();
        tabmodel.getDataVector().removeAllElements();
        tabmodel.fireTableDataChanged();
        rs = st.executeQuery("select * from tbl_menu");
        while (rs.next()){
            Object[] data = {
            rs.getString("kode_booking"),
            rs.getString("tgl_booking"),
            rs.getString("nama_team"),
            rs.getString("manager"),
            rs.getString("status"),
            rs.getString("harga_sewa"),
            rs.getString("dp"),
            rs.getString("tgl_sewa"),
            rs.getString("lama_main"),
            rs.getString("jam_masuk"),
             rs.getString("jam_keluar"),
             rs.getString("total_bayar"),
             rs.getString("sisa"),
            rs.getString("keterangan"),
            };
            tabmodel.addRow(data);
        }
     }catch(SQLException a){
     }
     }
    
    public void tglhariini(){
         java.util.Date sekarang = new java.util.Date();
         java.text.SimpleDateFormat tgl = new java.text.SimpleDateFormat("dd/MM/yyyy");
         tgl_bkng.setText(tgl.format(sekarang));
         tgl_bkng.setEditable(false);
     }
    
    public void harg(){
     int jumlah;
        if(member.isSelected()){
            hrg_sewa.setText("100000");
        } else{
            hrg_sewa.setText("150000");
        }
        hrg_sewa.setEditable(false);
     }
    
    
    public void totalin(){
     
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelKode = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelTanggal = new javax.swing.JLabel();
        mngr = new javax.swing.JTextField();
        labelNamaTeam = new javax.swing.JLabel();
        labelNope = new javax.swing.JLabel();
        nm_tm = new javax.swing.JTextField();
        hrg_sewa = new javax.swing.JTextField();
        labelNope1 = new javax.swing.JLabel();
        member = new javax.swing.JRadioButton();
        nonmember = new javax.swing.JRadioButton();
        dp = new javax.swing.JTextField();
        labelNope2 = new javax.swing.JLabel();
        tgl_bkng = new javax.swing.JTextField();
        kd_bkng = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelNope3 = new javax.swing.JLabel();
        tgl_sewa = new javax.swing.JTextField();
        labelNope4 = new javax.swing.JLabel();
        labelNope5 = new javax.swing.JLabel();
        jam_klr = new javax.swing.JTextField();
        labelNope6 = new javax.swing.JLabel();
        jam_msk = new javax.swing.JComboBox<>();
        lama_main = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sisa = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        bsimpan = new javax.swing.JButton();
        bdelete = new javax.swing.JButton();
        bupdate = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbldata = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Harmonious Calendar", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Futsal Kita");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(600, 600, 600)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addGap(217, 217, 217))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelKode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKode.setText("Kode Booking");

        jLabel2.setFont(new java.awt.Font("Glacial Indifference", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Registrasi Pemesanan");

        labelTanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTanggal.setText("Tanggal Pemesanan");

        mngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngrActionPerformed(evt);
            }
        });

        labelNamaTeam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNamaTeam.setText("Nama Team");

        labelNope.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope.setText("Manager Status");

        nm_tm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nm_tmActionPerformed(evt);
            }
        });

        hrg_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrg_sewaActionPerformed(evt);
            }
        });

        labelNope1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope1.setText("Harga Sewa");

        member.setText("Member");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });

        nonmember.setText("Nonmember");
        nonmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonmemberActionPerformed(evt);
            }
        });

        dp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dpActionPerformed(evt);
            }
        });

        labelNope2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope2.setText("DP");

        tgl_bkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_bkngActionPerformed(evt);
            }
        });

        kd_bkng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kd_bkngActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelKode)
                                    .addComponent(labelNope)
                                    .addComponent(labelNope1)
                                    .addComponent(labelNope2)
                                    .addComponent(labelNamaTeam))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(labelTanggal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nm_tm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dp, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(member)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                                .addComponent(nonmember))
                            .addComponent(hrg_sewa)
                            .addComponent(mngr)
                            .addComponent(kd_bkng, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tgl_bkng))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKode)
                    .addComponent(kd_bkng, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_bkng, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTanggal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm_tm, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaTeam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mngr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(member)
                    .addComponent(nonmember))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrg_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope2))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Glacial Indifference", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("Waktu Pemesanan");

        labelNope3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope3.setText("Tanggal Sewa");

        tgl_sewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_sewaActionPerformed(evt);
            }
        });

        labelNope4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope4.setText("Jam Masuk");

        labelNope5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope5.setText("Lama Bermain");

        jam_klr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jam_klrActionPerformed(evt);
            }
        });

        labelNope6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelNope6.setText("Jam Keluar");

        jam_msk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));

        lama_main.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        lama_main.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                lama_mainItemStateChanged(evt);
            }
        });
        lama_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lama_mainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 141, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNope3)
                            .addComponent(labelNope4)
                            .addComponent(labelNope5)
                            .addComponent(labelNope6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jam_klr)
                            .addComponent(tgl_sewa)
                            .addComponent(jam_msk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lama_main, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_sewa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jam_msk, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope4))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNope5)
                    .addComponent(lama_main, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jam_klr, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNope6))
                .addGap(0, 158, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total Bayar");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Sisa Pembayaran");

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        bdelete.setText("DELETE");
        bdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeleteActionPerformed(evt);
            }
        });

        bupdate.setText("UPDATE");
        bupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsimpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sisa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Kode", "Tanggal", "Waktu", "Nama Pemesan", "Nama Team", "No Handphone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbldata);

        jButton1.setText("LIHAT LAPORAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jButton3.setText("KEMBALI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(875, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1367, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel6);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 1364, 1087));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     private void tbldataMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        kd_bkng.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 0) + "");
        tgl_bkng.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 1) + "");
        
        nm_tm.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 3) + "");
        mngr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 4) + "");
        tabmodel.getValueAt(tbldata.getSelectedRow(), 5);
        String cek = (String) tabmodel.getValueAt(tbldata.getSelectedRow(), 5);
        if("Member".equals(cek)) {
            member.setSelected(true);
        } else {
            nonmember.setSelected(true);
        }
        hrg_sewa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 6) + "") ;
        dp.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 7) + "");
        tgl_sewa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 8) + "");
        lama_main.setSelectedItem(tabmodel.getValueAt(tbldata.getSelectedRow(), 9) + "");
        jam_msk.setSelectedItem(tabmodel.getValueAt(tbldata.getSelectedRow(), 10) + "");
        jam_klr.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 11) + "");
        total.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 12) + "");
        sisa.setText(tabmodel.getValueAt(tbldata.getSelectedRow(), 13) + "");
        
        bsimpan.setEnabled(false);
        bupdate.setEnabled(true);
        bdelete.setEnabled(true);
    }                 
    
    private void mngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mngrActionPerformed

    private void nm_tmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nm_tmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nm_tmActionPerformed

    private void hrg_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrg_sewaActionPerformed
        // TODO add your handling code here:
        String memberr, ttl; int totalll;
        if(member.isSelected()){
            memberr = member.getText();
            totalll = 100000;
            ttl = String.valueOf(totalll);
            hrg_sewa.setText(ttl);
        } else{
            memberr = nonmember.getText();
            totalll = 150000;
            ttl = String.valueOf(totalll);
            hrg_sewa.setText(ttl);
        }
        hrg_sewa.setEditable(false);

    }//GEN-LAST:event_hrg_sewaActionPerformed

    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
        hrg_sewa.setText("100000");
    }//GEN-LAST:event_memberActionPerformed

    private void nonmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonmemberActionPerformed
        // TODO add your handling code here:
        hrg_sewa.setText("150000");
    }//GEN-LAST:event_nonmemberActionPerformed

    private void dpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dpActionPerformed

    private void tgl_bkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_bkngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_bkngActionPerformed

    private void kd_bkngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kd_bkngActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kd_bkngActionPerformed

    private void tgl_sewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_sewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_sewaActionPerformed

    private void jam_klrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jam_klrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jam_klrActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        if(kd_bkng.getText().equals("") || tgl_bkng.getText().equals("")  || nm_tm.getText().equals("") || mngr.getText().equals("") || nm_tm.getText().equals("") || member.getText().equals("") || hrg_sewa.getText().equals("") || dp.getText().equals("") ||
            tgl_sewa.getText().equals("") || lama_main.getSelectedItem().equals("") || jam_msk.getSelectedItem().equals("") || jam_klr.getText().equals("") || total.getText().equals("") || sisa.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data tidak boleh ada yang kosong");
        } else{
            String memberr = "";
            int jumlah;
            if(member.isSelected()){
                memberr = member.getText();
                hrg_sewa.setText("100000");
            } else{
                memberr = nonmember.getText();
                hrg_sewa.setText("150000");
            }
            String ket; int dep, harg;
            dep = Integer.parseInt(dp.getText());
            harg = Integer.parseInt(hrg_sewa.getText());
            if(dep < harg){
                ket = "belum lunas!!";
            } else {
                ket = "sudah lunas!!";
            }
            try{
                cn = DriverManager.getConnection("jdbc:mysql://localhost/booking_lapangan?" + "user=root&password=");
                st = cn.createStatement();
                st.executeUpdate("insert into tbl_menu values('" + kd_bkng.getText()+ "','" + tgl_bkng.getText() +  "','" + nm_tm.getText() + "', '" + mngr.getText() + "', '" + memberr + "','" + hrg_sewa.getText()+ "','" + dp.getText()+ "','" + tgl_sewa.getText() + "','" + lama_main.getSelectedItem() + "','" + jam_msk.getSelectedItem() + "','" + jam_klr.getText() + "','" + total.getText() + "','"  + sisa.getText() + "','" + ket + "')");
                tampildata();
                reset();
                JOptionPane.showMessageDialog(null, "Berhasil disimpan!!");
            } catch(HeadlessException e){
            } catch (SQLException ex) {
                Logger.getLogger(frameutama.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeleteActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab = JOptionPane.showConfirmDialog(null, "ingin menghapus ?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                st = cn.createStatement();
                st.executeUpdate("delete from tbl_menu where " + "kode_booking='" + tabmodel.getValueAt(tbldata.getSelectedRow(), 0) + "'");
                tampildata();
                reset();

            }
        }catch (HeadlessException e){
        } catch (SQLException ex) {
             Logger.getLogger(frameutama.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_bdeleteActionPerformed

    private void bupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdateActionPerformed
        // TODO add your handling code here:
        String memberr;
        int jumlah;
        if(member.isSelected()){
            memberr = member.getText();
            hrg_sewa.setText("100000");
        } else{
            memberr = nonmember.getText();
            hrg_sewa.setText("150000");
        }
        String ket; int dep, totall;
        dep = Integer.parseInt(dp.getText());
        totall = Integer.parseInt(total.getText());
        if(dep < totall){
            ket = "Belum lunas!!";
        } else {
            ket = "Lunas!!";
        }
        
        try{
            cn = DriverManager.getConnection("jdbc:mysql://localhost/booking_lapangan?" + "user=root&password=");
            st = cn.createStatement();
            st.executeUpdate("update tbl_menu set tgl_booking = '" + tgl_bkng.getText() +  "', nama_team='" + nm_tm.getText() + "',manager='" + mngr.getText() + "',status='" + memberr + "', harga_sewa='" + hrg_sewa.getText() + "',dp='" + dp.getText() + "',tgl_sewa='" + tgl_sewa.getText() + "',lama_main='" + lama_main.getSelectedItem() + "',jam_masuk='" + jam_msk.getSelectedItem() + "',jam_keluar='" + jam_klr.getText() + "',total_bayar='" + total.getText() + "',sisa='" + sisa.getText() + "',keterangan='" + ket + "' where kode_booking='" + kd_bkng.getText() + "'");
            JOptionPane.showMessageDialog(null, "Data Berhasil  Diupdate!");
            tampildata();
            reset();
        } catch(HeadlessException e){
        } catch (SQLException ex) {
             Logger.getLogger(frameutama.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_bupdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       try{
         Desktop.getDesktop().browse(new URL("http://localhost:82/LaporanBarang/index.php").toURI());
     }catch(Exception e){
     }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        try{
            int log;
            if((log = JOptionPane.showConfirmDialog(null, "Yakin ingin Logout ?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0){
                framelogin m = new framelogin();
                m.setVisible(true);
                this.setVisible(false);
            }

        }catch(HeadlessException e){
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void lama_mainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_lama_mainItemStateChanged
        String totall, sisaa; int lama, harg, jml,sisaaa, dep;
        lama = Integer.parseInt((String) lama_main.getSelectedItem());
        dep = Integer.parseInt(dp.getText());
        harg = Integer.parseInt(hrg_sewa.getText());
        jml = lama * harg;
        totall = String.valueOf(jml);
        total.setText(totall);
        total.setEditable(false);
        sisaaa = jml - dep;
        sisaa = String.valueOf(sisaaa);
        sisa.setText(sisaa);
        sisa.setEditable(false);

        String hasil;
        int lila,msk, jmlh, totalll;
        lila = Integer.parseInt((String) lama_main.getSelectedItem());
        msk = Integer.parseInt((String) jam_msk.getSelectedItem());
        totalll = msk + lila;
        hasil = String.valueOf(totalll);
        jam_klr.setText(hasil + ".00");

    }//GEN-LAST:event_lama_mainItemStateChanged

    private void lama_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lama_mainActionPerformed
        // TODO add your handling code here:
        String totall, sisaa; int lama, harg, jml,sisaaa, dep;
        lama = Integer.parseInt((String) lama_main.getSelectedItem());
        dep = Integer.parseInt(dp.getText());
        harg = Integer.parseInt(hrg_sewa.getText());
        jml = lama * harg;
        totall = String.valueOf(jml);
        total.setText(totall);
        total.setEditable(false);
        sisaaa = jml - dep;
        sisaa = String.valueOf(sisaaa);
        sisa.setText(sisaa);
        sisa.setEditable(false);

    }//GEN-LAST:event_lama_mainActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         framepilihan pl = new framepilihan();
        pl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdelete;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton bupdate;
    private javax.swing.JTextField dp;
    private javax.swing.JTextField hrg_sewa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jam_klr;
    private javax.swing.JComboBox<String> jam_msk;
    private javax.swing.JTextField kd_bkng;
    private javax.swing.JLabel labelKode;
    private javax.swing.JLabel labelNamaTeam;
    private javax.swing.JLabel labelNope;
    private javax.swing.JLabel labelNope1;
    private javax.swing.JLabel labelNope2;
    private javax.swing.JLabel labelNope3;
    private javax.swing.JLabel labelNope4;
    private javax.swing.JLabel labelNope5;
    private javax.swing.JLabel labelNope6;
    private javax.swing.JLabel labelTanggal;
    private javax.swing.JComboBox<String> lama_main;
    private javax.swing.JButton logout;
    private javax.swing.JRadioButton member;
    private javax.swing.JTextField mngr;
    private javax.swing.JTextField nm_tm;
    private javax.swing.JRadioButton nonmember;
    private javax.swing.JTextField sisa;
    private javax.swing.JTable tbldata;
    private javax.swing.JTextField tgl_bkng;
    private javax.swing.JTextField tgl_sewa;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables

    
}
